#ifndef COMS_NETWORK_PACKET_TYPES_H
#define COMS_NETWORK_PACKET_TYPES_H

#define PACKET_TYPE_AUTH 0
#define SUB_PACKET_TYPE_AUTH_LOGIN 0
#define SUB_PACKET_TYPE_AUTH_LOADIN 1
#define SUB_PACKET_TYPE_AUTH_LOADOUT 2
#define SUB_PACKET_TYPE_AUTH_LOGOUT 3

#define PACKET_TYPE_MOB_STATE_SNAPSHOT 1
#define PACKET_TYPE_MOB_STATE_DELTA 2
#define PACKET_TYPE_MOB_STATE_POSITION_SNAPSHOT 3
#define PACKET_TYPE_MOB_STATE_POSITION_DELTA 4
#define PACKET_TYPE_MOB_STATE_ACTION_SNAPSHOT 5
#define PACKET_TYPE_MOB_STATE_ACTION_DELTA 6

#define PACKET_TYPE_MOB_LOOKS 7

#define PACKET_TYPE_CHAT_MSG 8
#define PACKET_TYPE_CHAT_ACTION 9
#define SUB_PACKET_TYPE_CHAT_FRIENDS_LOAD 1
#define SUB_PACKET_TYPE_CHAT_FRIENDS_ADD 2
#define SUB_PACKET_TYPE_CHAT_FRIENDS_REMOVE 3
#define SUB_PACKET_TYPE_CHAT_BLOCKED_LOAD 4
#define SUB_PACKET_TYPE_CHAT_BLOCKED_ADD 5
#define SUB_PACKET_TYPE_CHAT_BLOCKED_REMOVE 6
#define SUB_PACKET_TYPE_CHAT_FIND 7 // no data = list all

#define PACKET_TYPE_GUILD 10
#define SUB_PACKET_TYPE_GUILD_INVITE 0
#define SUB_PACKET_TYPE_GUILD_REQUEST 1
#define SUB_PACKET_TYPE_GUILD_JOIN 2
#define SUB_PACKET_TYPE_GUILD_LEAVE 3
#define SUB_PACKET_TYPE_GUILD_KICK 4
#define SUB_PACKET_TYPE_GUILD_FIND 5 // no data = list all
#define SUB_PACKET_TYPE_GUILD_LOAD_PUBLIC 6
#define SUB_PACKET_TYPE_GUILD_LOAD_PRIVATE 7
#define SUB_PACKET_TYPE_GUILD_LOAD_MEMBERS 8
#define SUB_PACKET_TYPE_GUILD_ACTION_CREATE 9
#define SUB_PACKET_TYPE_GUILD_ACTION_DELETE 10
#define SUB_PACKET_TYPE_GUILD_ACTION_PERMISSION 11 // Change permission of member
#define SUB_PACKET_TYPE_GUILD_ACTION_RENAME 12
#define SUB_PACKET_TYPE_GUILD_ACTION_DESCRIPTION 13
#define SUB_PACKET_TYPE_GUILD_ACTION_DESIGN 14
#define SUB_PACKET_TYPE_GUILD_ACTION_BANNER 15
// @todo guild hall actions (buy/sell/add furniture/...)

#define PACKET_TYPE_SHOP 11
#define SUB_PACKET_TYPE_SHOP_FIND 0
#define SUB_PACKET_TYPE_SHOP_SELL 1
#define SUB_PACKET_TYPE_SHOP_BUY 2
#define SUB_PACKET_TYPE_SHOP_BID 3
#define SUB_PACKET_TYPE_SHOP_CANCEL 4

#define PACKET_TYPE_SHOP 12
#define SUB_PACKET_TYPE_SHOP_FIND 0
#define SUB_PACKET_TYPE_SHOP_SELL 1
#define SUB_PACKET_TYPE_SHOP_BUY 2
#define SUB_PACKET_TYPE_SHOP_BID 3
#define SUB_PACKET_TYPE_SHOP_CANCEL 4

#define PACKET_TYPE_GROUP 13
#define SUB_PACKET_TYPE_GROUP_INVITE 0
#define SUB_PACKET_TYPE_GROUP_JOIN 1
#define SUB_PACKET_TYPE_GROUP_LEAVE 2
#define SUB_PACKET_TYPE_GROUP_KICK 3
#define SUB_PACKET_TYPE_GROUP_FIND 4

#define PACKET_TYPE_INTERACT 14

#define PACKET_TYPE_MOB_ITEM 15
#define SUB_PACKET_TYPE_MOB_ITEM_PICKUP 0
#define SUB_PACKET_TYPE_MOB_ITEM_USE 1
#define SUB_PACKET_TYPE_MOB_ITEM_EQUIP 2
#define SUB_PACKET_TYPE_MOB_ITEM_DROP 3
#define SUB_PACKET_TYPE_MOB_ITEM_MOVE 4

#define PACKET_TYPE_GM_ACTION 16
#define SUB_PACKET_TYPE_GM_ACTION_MOVE 0 // moves any type of mob to any location
#define SUB_PACKET_TYPE_GM_ACTION_KILL 1
#define SUB_PACKET_TYPE_GM_ACTION_SPAWN 2
#define SUB_PACKET_TYPE_GM_ACTION_KICK 3
#define SUB_PACKET_TYPE_GM_ACTION_BAN 4
#define SUB_PACKET_TYPE_GM_ACTION_CHAT_REMOVE 5
#define SUB_PACKET_TYPE_GM_ACTION_AWARD_QUEST 6
#define SUB_PACKET_TYPE_GM_ACTION_RESET_QUEST 7

#endif