#ifndef TOS_MODELS_MOB_LIST_H
#define TOS_MODELS_MOB_LIST_H

#define MOB_LIST_COW 0x01
#define MOB_LIST_CHICKEN 0x02
#define MOB_LIST_PIG 0x03
#define MOB_LIST_DOG 0x04
#define MOB_LIST_CAT 0x05
#define MOB_LIST_HORSE 0x06
#define MOB_LIST_CROW 0x07

#define SIZE_MOB_LIST 0x07

#endif