#ifndef COMS_MODELS_MOB_CATEGORY_H
#define COMS_MODELS_MOB_CATEGORY_H

#define MOB_CATEGORY_REGULAR 0x01
#define MOB_CATEGORY_CHAMPION 0x02
#define MOB_CATEGORY_BOSS 0x03
#define MOB_CATEGORY_WORLD_BOSS 0x04
#define MOB_CATEGORY_SINGULARITY 0x05
#define MOB_CATEGORY_ANIMAL 0x06
#define MOB_CATEGORY_NPC 0x07
#define MOB_CATEGORY_PLAYER 0x08

#define SIZE_MOB_CATEGORY 0x08

#endif