/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#ifndef COMS_JINGGA_HTTP_HEADER_KEY_H
#define COMS_JINGGA_HTTP_HEADER_KEY_H

#include "../stdlib/Types.h"

enum HttpHeaderKey : byte {
    // Standard HTTP/1.1 & HTTP/2 Headers (RFC 9110, 9113, etc.)
    HTTP_HEADER_KEY_HOST,
    HTTP_HEADER_KEY_USER_AGENT,
    HTTP_HEADER_KEY_ACCEPT,
    HTTP_HEADER_KEY_ACCEPT_CHARSET,
    HTTP_HEADER_KEY_ACCEPT_ENCODING,
    HTTP_HEADER_KEY_ACCEPT_LANGUAGE,
    HTTP_HEADER_KEY_ACCEPT_DATETIME,
    HTTP_HEADER_KEY_ACCEPT_PATCH,
    HTTP_HEADER_KEY_ACCEPT_RANGES,
    HTTP_HEADER_KEY_AGE,
    HTTP_HEADER_KEY_ALLOW,
    HTTP_HEADER_KEY_AUTHORIZATION,
    HTTP_HEADER_KEY_CACHE_CONTROL,
    HTTP_HEADER_KEY_CONNECTION,
    HTTP_HEADER_KEY_CONTENT_DISPOSITION,
    HTTP_HEADER_KEY_CONTENT_ENCODING,
    HTTP_HEADER_KEY_CONTENT_LANGUAGE,
    HTTP_HEADER_KEY_CONTENT_LENGTH,
    HTTP_HEADER_KEY_CONTENT_LOCATION,
    HTTP_HEADER_KEY_CONTENT_MD5,
    HTTP_HEADER_KEY_CONTENT_RANGE,
    HTTP_HEADER_KEY_CONTENT_TYPE,
    HTTP_HEADER_KEY_COOKIE,
    HTTP_HEADER_KEY_DATE,
    HTTP_HEADER_KEY_ETAG,
    HTTP_HEADER_KEY_EXPECT,
    HTTP_HEADER_KEY_EXPIRES,
    HTTP_HEADER_KEY_FROM,
    HTTP_HEADER_KEY_IF_MATCH,
    HTTP_HEADER_KEY_IF_MODIFIED_SINCE,
    HTTP_HEADER_KEY_IF_NONE_MATCH,
    HTTP_HEADER_KEY_IF_RANGE,
    HTTP_HEADER_KEY_IF_UNMODIFIED_SINCE,
    HTTP_HEADER_KEY_LAST_MODIFIED,
    HTTP_HEADER_KEY_LINK,
    HTTP_HEADER_KEY_LOCATION,
    HTTP_HEADER_KEY_MAX_FORWARDS,
    HTTP_HEADER_KEY_ORIGIN,
    HTTP_HEADER_KEY_PRAGMA,
    HTTP_HEADER_KEY_PROXY_AUTHENTICATE,
    HTTP_HEADER_KEY_PROXY_AUTHORIZATION,
    HTTP_HEADER_KEY_RANGE,
    HTTP_HEADER_KEY_REFERER,
    HTTP_HEADER_KEY_RETRY_AFTER,
    HTTP_HEADER_KEY_SERVER,
    HTTP_HEADER_KEY_SET_COOKIE,
    HTTP_HEADER_KEY_STRICT_TRANSPORT_SECURITY,
    HTTP_HEADER_KEY_TE,
    HTTP_HEADER_KEY_TRAILER,
    HTTP_HEADER_KEY_TRANSFER_ENCODING,
    HTTP_HEADER_KEY_UPGRADE,
    HTTP_HEADER_KEY_VARY,
    HTTP_HEADER_KEY_VIA,
    HTTP_HEADER_KEY_WARNING,
    HTTP_HEADER_KEY_WWW_AUTHENTICATE,

    // Common Non-Standard (X-*) and Extension Headers
    HTTP_HEADER_KEY_X_FORWARDED_FOR,
    HTTP_HEADER_KEY_X_FORWARDED_HOST,
    HTTP_HEADER_KEY_X_FORWARDED_PROTO,
    HTTP_HEADER_KEY_X_REQUESTED_WITH,
    HTTP_HEADER_KEY_X_CSRF_TOKEN,
    HTTP_HEADER_KEY_X_XSS_PROTECTION,
    HTTP_HEADER_KEY_X_CONTENT_TYPE_OPTIONS,
    HTTP_HEADER_KEY_X_FRAME_OPTIONS,
    HTTP_HEADER_KEY_X_POWERED_BY,
    HTTP_HEADER_KEY_X_UPLOAD_ID,
    HTTP_HEADER_KEY_X_RATE_LIMIT_LIMIT,
    HTTP_HEADER_KEY_X_RATE_LIMIT_REMAINING,
    HTTP_HEADER_KEY_X_RATE_LIMIT_RESET,
    HTTP_HEADER_KEY_X_UA_COMPATIBLE,
    HTTP_HEADER_KEY_X_DNS_PREFETCH_CONTROL,
    HTTP_HEADER_KEY_X_DOWNLOAD_OPTIONS,
    HTTP_HEADER_KEY_X_PERMITTED_CROSS_DOMAIN_POLICIES,

    // CORS Headers
    HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_ORIGIN,
    HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_CREDENTIALS,
    HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_HEADERS,
    HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_METHODS,
    HTTP_HEADER_KEY_ACCESS_CONTROL_EXPOSE_HEADERS,
    HTTP_HEADER_KEY_ACCESS_CONTROL_MAX_AGE,
    HTTP_HEADER_KEY_ACCESS_CONTROL_REQUEST_HEADERS,
    HTTP_HEADER_KEY_ACCESS_CONTROL_REQUEST_METHOD,

    // Security Headers
    HTTP_HEADER_KEY_CONTENT_SECURITY_POLICY,
    HTTP_HEADER_KEY_PERMISSIONS_POLICY,
    HTTP_HEADER_KEY_REFERRER_POLICY,
    HTTP_HEADER_KEY_EXPECT_CT,
    HTTP_HEADER_KEY_FEATURE_POLICY,
    HTTP_HEADER_KEY_CROSS_ORIGIN_EMBEDDER_POLICY,
    HTTP_HEADER_KEY_CROSS_ORIGIN_OPENER_POLICY,
    HTTP_HEADER_KEY_CROSS_ORIGIN_RESOURCE_POLICY,

    // WebSocket Headers
    HTTP_HEADER_KEY_SEC_WEBSOCKET_KEY,
    HTTP_HEADER_KEY_SEC_WEBSOCKET_ACCEPT,
    HTTP_HEADER_KEY_SEC_WEBSOCKET_VERSION,
    HTTP_HEADER_KEY_SEC_WEBSOCKET_PROTOCOL,
    HTTP_HEADER_KEY_SEC_WEBSOCKET_EXTENSIONS,

    // HTTP/3 and QUIC Headers
    HTTP_HEADER_KEY_ALT_SVC,
    HTTP_HEADER_KEY_EARLY_DATA,

    // Cloud & CDN Headers
    HTTP_HEADER_KEY_CF_CONNECTING_IP,
    HTTP_HEADER_KEY_CF_IPCOUNTRY,
    HTTP_HEADER_KEY_CF_RAY,
    HTTP_HEADER_KEY_TRUE_CLIENT_IP,
    HTTP_HEADER_KEY_X_AMZ_CF_ID,
    HTTP_HEADER_KEY_X_AMZN_TRACE_ID,

    // Custom/Experimental Headers
    HTTP_HEADER_KEY_DNT, // Do Not Track
    HTTP_HEADER_KEY_SAVE_DATA,
    HTTP_HEADER_KEY_DOWNLINK,
    HTTP_HEADER_KEY_ECT, // Effective Connection Type
    HTTP_HEADER_KEY_RTT,
    HTTP_HEADER_KEY_PURPOSE,
    HTTP_HEADER_KEY_SEC_FETCH_SITE,
    HTTP_HEADER_KEY_SEC_FETCH_MODE,
    HTTP_HEADER_KEY_SEC_FETCH_USER,
    HTTP_HEADER_KEY_SEC_FETCH_DEST,
    HTTP_HEADER_KEY_SERVICE_WORKER_NAVIGATION_PRELOAD,
    HTTP_HEADER_KEY_LAST_EVENT_ID,
    HTTP_HEADER_KEY_REPORT_TO,
    HTTP_HEADER_KEY_PRIORITY,
    HTTP_HEADER_KEY_SIGNATURE,
    HTTP_HEADER_KEY_SIGNATURE_KEY,
    HTTP_HEADER_KEY_FORWARDED,
    HTTP_HEADER_KEY_ORIGINAL_METHOD,
    HTTP_HEADER_KEY_ORIGINAL_URL,
    HTTP_HEADER_KEY_ORIGINAL_HOST,
};

#endif