/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#ifndef TOS_MODELS_ITEM_EQUIPMENT_SLOTS_H
#define TOS_MODELS_ITEM_EQUIPMENT_SLOTS_H

#define EQUIPMENT_SLOT_HEAD 0x01
#define EQUIPMENT_SLOT_NECK 0x02
#define EQUIPMENT_SLOT_BODY 0x03
#define EQUIPMENT_SLOT_BELT 0x04
#define EQUIPMENT_SLOT_PANTS 0x05
#define EQUIPMENT_SLOT_BOOTS 0x06
#define EQUIPMENT_SLOT_RING 0x07
#define EQUIPMENT_SLOT_MAIN_HAND 0x08
#define EQUIPMENT_SLOT_OFF_HAND 0x09
#define EQUIPMENT_SLOT_ARMS 0x0A
#define EQUIPMENT_SLOT_BELT_ATTACHMENT 0x0B
#define EQUIPMENT_SLOT_SHOULDER 0x0C
#define EQUIPMENT_SLOT_BACK 0x0D
#define EQUIPMENT_SLOT_HANDS 0x0E

#endif