/**
 * Jingga
 *
 * @package   Utils
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#ifndef TOS_ANIMATION_EASE_TYPE_H
#define TOS_ANIMATION_EASE_TYPE_H

#include "../stdlib/Types.h"

enum AnimationEaseType : byte {
    ANIMATION_LINEAR,
    ANIMATION_EASE_DISCRETE,
    ANIMATION_EASE_IN_SINE,
    ANIMATION_EASE_OUT_SINE,
    ANIMATION_EASE_IN_OUT_SINE,
    ANIMATION_EASE_IN_QUAD,
    ANIMATION_EASE_OUT_QUAD,
    ANIMATION_EASE_IN_OUT_QUAD,
    ANIMATION_EASE_IN_CUBIC,
    ANIMATION_EASE_OUT_CUBIC,
    ANIMATION_EASE_IN_OUT_CUBIC,
    ANIMATION_EASE_IN_QUART,
    ANIMATION_EASE_OUT_QUART,
    ANIMATION_EASE_IN_OUT_QUART,
    ANIMATION_EASE_IN_QUINT,
    ANIMATION_EASE_OUT_QUINT,
    ANIMATION_EASE_IN_OUT_QUINT,
    ANIMATION_EASE_IN_EXPO,
    ANIMATION_EASE_OUT_EXPO,
    ANIMATION_EASE_IN_OUT_EXPO,
    ANIMATION_EASE_IN_CIRC,
    ANIMATION_EASE_OUT_CIRC,
    ANIMATION_EASE_IN_OUT_CIRC,
    ANIMATION_EASE_IN_BACK,
    ANIMATION_EASE_OUT_BACK,
    ANIMATION_EASE_IN_OUT_BACK,
    ANIMATION_EASE_IN_ELASTIC,
    ANIMATION_EASE_OUT_ELASTIC,
    ANIMATION_EASE_IN_OUT_ELASTIC,
    ANIMATION_EASE_IN_BOUNCE,
    ANIMATION_EASE_OUT_BOUNCE,
    ANIMATION_EASE_IN_OUT_BOUNCE
};

#endif