#ifndef COMS_MODELS_SKILL_AOE_SHAPE_H
#define COMS_MODELS_SKILL_AOE_SHAPE_H

enum AoeShape {
    AOE_SHAPE_RECTANGLE,
    AOE_SHAPE_CIRCLE,
    AOE_SHAPE_SPHEAR,
    AOE_SHAPE_BOX,
    AOE_SHAPE_FUNNEL
};

#endif