#ifndef TOS_MODELS_SKILL_PROJECTILE_DISTRIBUTION_H
#define TOS_MODELS_SKILL_PROJECTILE_DISTRIBUTION_H

enum ProjectileDistribution
{
    PROJECTILE_DISTRIBUTION_HORIZONTAL,
    PROJECTILE_DISTRIBUTION_LINE,
    PROJECTILE_DISTRIBUTION_CIRCLE
};

#endif