#ifndef COMS_MODELS_SKILL_STATS_TARGET_H
#define COMS_MODELS_SKILL_STATS_TARGET_H

enum StatsTarget {
    STATS_TARGET_NONE,

    STATS_TARGET_SELF,

    STATS_TARGET_ENEMY,
    STATS_TARGET_ENEMY_AOE,
    STATS_TARGET_ENEMY_AURA,

    STATS_TARGET_ALLY,
    STATS_TARGET_ALLY_AOE,
    STATS_TARGET_ALLY_AURA
};

#endif