#ifndef COMS_MODELS_OBJECT_TYPES_H
#define COMS_MODELS_OBJECT_TYPES_H

#define OBJECT_TYPE_LADDER 0x01
#define OBJECT_TYPE_ROPE 0x02
#define OBJECT_TYPE_VINES 0x03
#define OBJECT_TYPE_ORE 0x04
#define OBJECT_TYPE_BLOCK 0x05
#define OBJECT_TYPE_HERB 0x06
#define OBJECT_TYPE_LIQUID 0x07
#define OBJECT_TYPE_PARTICLE 0x08
#define OBJECT_TYPE_FARMING 0x09
#define OBJECT_TYPE_PLANT 0x0A
#define OBJECT_TYPE_STATIC_OBJECT 0x0B
#define OBJECT_TYPE_DYNAMIC_OBJECT 0x0C
#define OBJECT_TYPE_STATIC_TEXTURE 0x0D
#define OBJECT_TYPE_FIXED_LIGHT_SOURCE 0x0E
#define OBJECT_TYPE_DYNAMIC_LIGHT_SOURCE 0x0F
#define OBJECT_TYPE_DYNAMIC_TEXTURE 0x10
#define OBJECT_TYPE_VEHICLE 0x11
#define OBJECT_TYPE_MACHINE 0x12
#define OBJECT_TYPE_MOB 0x13
#define OBJECT_TYPE_FOOD 0x14

#define SIZE_OBJECT_TYPE 0x14

#endif