name: CI/CD

on: [push]

jobs:
  code-tests:
    strategy:
      matrix:
        platform: [x86, x64]
        os: [ubuntu-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }} / ${{ matrix.platform }}'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: '${{ matrix.platform }}'
      - name: Run tests
        run: |
          chmod +x ./tests/test.sh
          ./tests/test.sh
