#ifndef COMS_MODELS_SETTING_TYPES_H
#define COMS_MODELS_SETTING_TYPES_H

enum SettingGpuDetail {
    SETTING_TYPE_GPU_DETAIL_CUSTOM,
    SETTING_TYPE_GPU_DETAIL_VLOW,
    SETTING_TYPE_GPU_DETAIL_LOW,
    SETTING_TYPE_GPU_DETAIL_MEDIUM,
    SETTING_TYPE_GPU_DETAIL_HIGH,
    SETTING_TYPE_GPU_DETAIL_VHIGH,
    SETTING_TYPE_GPU_DETAIL_ULTRA,
    SETTING_TYPE_GPU_DETAIL_NEXTGEN
};

enum SettingPlayerPerspective {
    SETTING_TYPE_PERSPECTIVE_FIRST,
    SETTING_TYPE_PERSPECTIVE_THIRD,
    SETTING_TYPE_PERSPECTIVE_ISOMETRIC
};

enum SettingVSync {
    SETTING_TYPE_SYNC_NONE,
    SETTING_TYPE_SYNC_V,
    SETTING_TYPE_SYNC_ADAPTIVE,
    SETTING_TYPE_SYNC_FAST
};

enum SettingAspectRatio {
    SETTING_TYPE_ASPEC_RATIO_4x3,
    SETTING_TYPE_ASPEC_RATIO_16x9,
    SETTING_TYPE_ASPEC_RATIO_16x10,
    SETTING_TYPE_ASPEC_RATIO_21x9
};

enum SettingScreenResolution {
    SETTING_TYPE_SCREEN_RESOLUTION_800x600,
    SETTING_TYPE_SCREEN_RESOLUTION_1024x768,
    SETTING_TYPE_SCREEN_RESOLUTION_1280x720,
    SETTING_TYPE_SCREEN_RESOLUTION_1280x800,
    SETTING_TYPE_SCREEN_RESOLUTION_1280x1024,
    SETTING_TYPE_SCREEN_RESOLUTION_1360x768,
    SETTING_TYPE_SCREEN_RESOLUTION_1366x768,
    SETTING_TYPE_SCREEN_RESOLUTION_1440x900,
    SETTING_TYPE_SCREEN_RESOLUTION_1536x864,
    SETTING_TYPE_SCREEN_RESOLUTION_1600x900,
    SETTING_TYPE_SCREEN_RESOLUTION_1600x1200,
    SETTING_TYPE_SCREEN_RESOLUTION_1680x1050,
    SETTING_TYPE_SCREEN_RESOLUTION_1920x1080,
    SETTING_TYPE_SCREEN_RESOLUTION_1920x1200,
    SETTING_TYPE_SCREEN_RESOLUTION_2048x1152,
    SETTING_TYPE_SCREEN_RESOLUTION_2048x1536,
    SETTING_TYPE_SCREEN_RESOLUTION_2560x1080,
    SETTING_TYPE_SCREEN_RESOLUTION_2560x1440,
    SETTING_TYPE_SCREEN_RESOLUTION_2560x1600,
    SETTING_TYPE_SCREEN_RESOLUTION_3440x1440,
    SETTING_TYPE_SCREEN_RESOLUTION_3840x2160
};

enum SettingWindows {
    SETTING_TYPE_WINDOW_NONE,
    SETTING_TYPE_WINDOW_CHAT,
    SETTING_TYPE_WINDOW_MAP,
    SETTING_TYPE_WINDOW_RANKING,
    SETTING_TYPE_WINDOW_SHOP,
    SETTING_TYPE_WINDOW_STATS,
    SETTING_TYPE_WINDOW_GROUPS,
    SETTING_TYPE_WINDOW_PET // Pet "tamagochi" window
};

enum SettingWindowMode {
    SETTING_TYPE_WINDOW_MODE_FULLSCREEN,
    SETTING_TYPE_WINDOW_MODE_WINDOWED_FULLSCREEN,
    SETTING_TYPE_WINDOW_MODE_WINDOWED
};

#define SETTING_TYPE_DISABLED 0x00
#define SETTING_TYPE_UNLIMITED 0x00

enum SettingDebugVisibility {
    SETTING_DEBUG_VISIBILITY_WIREFRAME = 1 << 0,
    SETTING_DEBUG_VISIBILITY_DEBUG = 1 << 1,
    SETTING_DEBUG_VISIBILITY_3D = 1 << 2,
    SETTING_DEBUG_VISIBILITY_NORMALS = 1 << 3
};

enum SettingUiVisibility {
    SETTING_UI_VISIBILITY_FPS = 1 << 0,
    SETTING_UI_VISIBILITY_APM = 1 << 1,
    SETTING_UI_VISIBILITY_NET_GRAPH = 1 << 2,
    SETTING_UI_VISIBILITY_CONSOLE = 1 << 3,
    SETTING_UI_VISIBILITY_HOTKEYS = 1 << 4,
    SETTING_UI_VISIBILITY_XP_BAR = 1 << 5,
    SETTING_UI_VISIBILITY_COOLDOWN_TIMER = 1 << 6,
    SETTING_UI_VISIBILITY_MINIMAP = 1 << 7,
    SETTING_UI_VISIBILITY_CHAT = 1 << 8,
    SETTING_UI_VISIBILITY_CLOCK = 1 << 9,
    SETTING_UI_VISIBILITY_SUBTITLES = 1 << 10,
    SETTING_UI_VISIBILITY_BAR = 1 << 11,
    SETTING_UI_VISIBILITY_HEALTH = 1 << 12,
    SETTING_UI_VISIBILITY_RESOURCE = 1 << 13,
    SETTING_UI_VISIBILITY_INFO = 1 << 14 // = e.g. quest info
};

enum SettingGameVisibility {
    SETTING_GAME_VISIBILITY_BAR_SELF = 1 << 0,
    SETTING_GAME_VISIBILITY_BAR_PLAYER = 1 << 1,
    SETTING_GAME_VISIBILITY_BAR_OTHER = 1 << 2,
    SETTING_GAME_VISIBILITY_BAR_NUMBERS = 1 << 3,
    SETTING_GAME_VISIBILITY_BUFFS_SELF = 1 << 4,
    SETTING_GAME_VISIBILITY_BUFFS_PLAYER = 1 << 5,
    SETTING_GAME_VISIBILITY_BUFFS_OTHER = 1 << 6,
    SETTING_GAME_VISIBILITY_NAME_SELF = 1 << 7,
    SETTING_GAME_VISIBILITY_NAME_PLAYER = 1 << 8,
    SETTING_GAME_VISIBILITY_NAME_OTHER = 1 << 9,
    SETTING_GAME_VISIBILITY_TITLE_SELF = 1 << 10,
    SETTING_GAME_VISIBILITY_TITLE_PLAYER = 1 << 11,
    SETTING_GAME_VISIBILITY_TITLE_OTHER = 1 << 12,
    SETTING_GAME_VISIBILITY_DMG_NUMBERS = 1 << 13,
    SETTING_GAME_VISIBILITY_XP_NUMBERS = 1 << 14,
    SETTING_GAME_VISIBILITY_EFFECTS = 1 << 15
};

enum InputDeviceType {
    SETTING_INPUT_DEVICE_TYPE_MOUSE_KEYBOARD,
    SETTING_INPUT_DEVICE_TYPE_CONTROLLER,
};

#endif